update

diff --git a/0x05-processes_and_signals/67-stop_me_if_you_can b/0x05-processes_and_signals/67-stop_me_if_you_can
--- a/0x05-processes_and_signals/67-stop_me_if_you_can
+++ b/0x05-processes_and_signals/67-stop_me_if_you_can
@@ -1,18 +1,15 @@
-#!/usr/bin/env bash
-# This script kills the 7-highlander process
-# And displays "I am invincible!!" upon receiving a SIGTERM signal
-
-# Function to handle the SIGTERM signal
-function terminate {
-  echo "I am invincible!!"
-  exit 0
-}
-
-# Trap the SIGTERM signal
-trap terminate SIGTERM
+#!/bin/bash
 
 # Get the PID of the 7-highlander process
-pid=$(pgrep -f '7-highlander')
+pid=$(pgrep -f 7-highlander)
 
-# Kill the 7-highlander process using its PID
-kill $pid
+# Check if the process was found
+if [ -z "$pid" ]; then
+    echo "7-highlander process not found"
+    exit 1
+else
+    echo "Killed"
+    kill $pid
+    exit 0
+fi
+
